### PR TITLE
Port read-chars, read-event and read-char-exclusive from lread.c

### LINKED ISSUE #923: Port read-char, read-event, read-char-exclusive
These three functions from `lread.c` are all pretty similar, so they might as well be ported together.

```c
DEFUN ("read-char", Fread_char, Sread_char, 0, 3, 0,
       doc: /* Read a character from the command input (keyboard or macro).
It is returned as a number.
If the character has modifiers, they are resolved and reflected to the
character code if possible (e.g. C-SPC -> 0).

If the user generates an event which is not a character (i.e. a mouse
click or function key event), `read-char' signals an error.  As an
exception, switch-frame events are put off until non-character events
can be read.
If you want to read non-character events, or ignore them, call
`read-event' or `read-char-exclusive' instead.

If the optional argument PROMPT is non-nil, display that as a prompt.
If the optional argument INHERIT-INPUT-METHOD is non-nil and some
input method is turned on in the current buffer, that input method
is used for reading a character.
If the optional argument SECONDS is non-nil, it should be a number
specifying the maximum number of seconds to wait for input.  If no
input arrives in that time, return nil.  SECONDS may be a
floating-point value.  */)
  (Lisp_Object prompt, Lisp_Object inherit_input_method, Lisp_Object seconds)
{
  Lisp_Object val;

  if (! NILP (prompt))
    message_with_string ("%s", prompt, 0);
  val = read_filtered_event (1, 1, 1, ! NILP (inherit_input_method), seconds);

  return (NILP (val) ? Qnil
	  : make_number (char_resolve_modifier_mask (XINT (val))));
}

DEFUN ("read-event", Fread_event, Sread_event, 0, 3, 0,
       doc: /* Read an event object from the input stream.
If the optional argument PROMPT is non-nil, display that as a prompt.
If the optional argument INHERIT-INPUT-METHOD is non-nil and some
input method is turned on in the current buffer, that input method
is used for reading a character.
If the optional argument SECONDS is non-nil, it should be a number
specifying the maximum number of seconds to wait for input.  If no
input arrives in that time, return nil.  SECONDS may be a
floating-point value.  */)
  (Lisp_Object prompt, Lisp_Object inherit_input_method, Lisp_Object seconds)
{
  if (! NILP (prompt))
    message_with_string ("%s", prompt, 0);
  return read_filtered_event (0, 0, 0, ! NILP (inherit_input_method), seconds);
}

DEFUN ("read-char-exclusive", Fread_char_exclusive, Sread_char_exclusive, 0, 3, 0,
       doc: /* Read a character from the command input (keyboard or macro).
It is returned as a number.  Non-character events are ignored.
If the character has modifiers, they are resolved and reflected to the
character code if possible (e.g. C-SPC -> 0).

If the optional argument PROMPT is non-nil, display that as a prompt.
If the optional argument INHERIT-INPUT-METHOD is non-nil and some
input method is turned on in the current buffer, that input method
is used for reading a character.
If the optional argument SECONDS is non-nil, it should be a number
specifying the maximum number of seconds to wait for input.  If no
input arrives in that time, return nil.  SECONDS may be a
floating-point value.  */)
  (Lisp_Object prompt, Lisp_Object inherit_input_method, Lisp_Object seconds)
{
  Lisp_Object val;

  if (! NILP (prompt))
    message_with_string ("%s", prompt, 0);

  val = read_filtered_event (1, 1, 0, ! NILP (inherit_input_method), seconds);

  return (NILP (val) ? Qnil
	  : make_number (char_resolve_modifier_mask (XINT (val))));
}
```

### PR DESCRIPTION
**Pull request by Bira**
These three small functions are pretty much direct translations of their C counterparts, and all make use of the much more complex `read_filtered_event` C function, which is definitely beyond my ability to port. 

Closes #923 .

### CODE REVIEW

File: rust_src/src/lread.rs [hunk 1]
```diff
@@ -309,4 +310,100 @@ pub fn eval_region(
...
+    inherit_input_method: LispObject,
+    seconds: LispObject,
+) -> LispObject {
+    if !prompt.is_nil() {
+        message_with_string!("%s", prompt, false);
+    }
+
+    let val =
+        unsafe { read_filtered_event(true, true, true, !inherit_input_method.is_nil(), seconds) };
+
```
Comment (shaleh) [inline rust_src/src/lread.rs]: I believe something like this matches the original intent but is closer to idiomatic Rust if the return type is changed to `Option<EmacsInt>`. `read_char_exclusive` follows a similar pattern.

```
match val.into() {
    Some(num) => Some(unsafe { char_resolve_modifier_mask(num) }),
    None => None,
}
```

File: rust_src/src/lread.rs [hunk 2]
```diff
@@ -309,4 +310,100 @@ pub fn eval_region(
...
+pub fn read_event(
+    prompt: LispObject,
+    inherit_input_method: LispObject,
+    seconds: LispObject,
+) -> LispObject {
+    if !prompt.is_nil() {
+        message_with_string!("%s", prompt, false);
+    }
+
+    unsafe { read_filtered_event(false, false, false, inherit_input_method.is_nil(), seconds) }
```
Comment (shaleh) [inline rust_src/src/lread.rs]:
```suggestion
    unsafe { read_filtered_event(false, false, false, !inherit_input_method.is_nil(), seconds) }
```

Missed the `!`.

**Comment by shaleh** [comment]
You were right to pass on `read_filtered_event`. That one is a little tricky. I am about half through porting it and should have something in a day or three.

**Comment by brotzeit** [comment]
@Bira I added you to the project. You can merge your PRs now.

**Comment by Bira** [comment]
Thanks, @brotzeit ! The merge button isn't appearing to me on this particular PR, it says I need write access. Do I have to do anything else before I can merge?

**Comment by brotzeit** [comment]
Did you receive a mail ?

**Comment by Bira** [comment]
Ah yes, just saw it and accepted. Sorry for the confusion! 

What's the accepted way of merging PRs in remacs? would "squash and merge" be OK?

**Comment by brotzeit** [comment]
In this case a Squash would be best.

**Comment by Bira** [comment]
Thanks!

**Comment by shaleh** [comment]
In general we squash everything but merges from emacs.
